<?php

return [
    [
        'title' => 'test title 1',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => 199,
        'new' => true,
        'img'  => '/img/img_product1.png',
    ],
    [
        'title' => 'test title 2',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product2.png',
    ],
    [
        'title' => 'test title 3',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 125,
        'new' => true,
        'discountCost' => null,
        'img'  => '/img/img_product3.png',
    ],
    [
        'title' => 'test title 4',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 111,
        'discountCost' => 90,
        'new' => false,
        'img'  => '/img/img_product4.png',
    ],
    [
        'title' => 'test title 5',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => true,
        'img'  => '/img/img_product5.png',
    ],
    [
        'title' => 'test title 6',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => true,
        'img'  => '/img/img_product6.png',
    ],
    [
        'title' => 'test title 7',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product7.png',
    ],
    [
        'title' => 'test title 8',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product8.png',
    ],
    [
        'title' => 'test title 9',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product9.png',
    ],
];